In [4]:
import torch

In [5]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[2, 1, 1],
        [4, 2, 2]])
tensor([[2, 4, 4],
        [1, 2, 4]])


In [6]:
a + b

tensor([[4, 5, 5],
        [5, 4, 6]])

In [7]:
torch.add(a,b)

tensor([[4, 5, 5],
        [5, 4, 6]])

In [8]:
result = torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[4., 5., 5.],
        [5., 4., 6.]])

In [9]:
result

tensor([[4., 5., 5.],
        [5., 4., 6.]])

In [10]:
# a = a + b
# 注意 任何使张量tensor会发生变化的操作都有一个前缀'_'，例如：a.add_(),b.sub_()
a.add_(b)
a

tensor([[4, 5, 5],
        [5, 4, 6]])

In [11]:
a - b

tensor([[2, 1, 1],
        [4, 2, 2]])

In [12]:
a * b

tensor([[ 8, 20, 20],
        [ 5,  8, 24]])

In [13]:
a / b

tensor([[2.0000, 1.2500, 1.2500],
        [5.0000, 2.0000, 1.5000]])

In [14]:
# 取余数
a % b

tensor([[0, 1, 1],
        [0, 0, 2]])

In [15]:
# 取整
a // b

tensor([[2, 1, 1],
        [5, 2, 1]])

In [16]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [17]:
a

tensor([[4, 5, 5],
        [5, 4, 6]])

In [18]:
torch.matmul(a,tensor)

RuntimeError: expected m1 and m2 to have the same dtype, but got: __int64 != float

In [19]:
a.dtype

torch.int64

In [20]:
tensor.dtype

torch.float32

In [21]:
a = a.float()
a.dtype

torch.float32

In [22]:
torch.matmul(a,tensor) # 2*3 3*5 = 2*5

tensor([[14., 14., 14., 14., 14.],
        [15., 15., 15., 15., 15.]])

In [23]:
# 矩阵的转置操作
a.T

tensor([[4., 5.],
        [5., 4.],
        [5., 6.]])