In [1]:
import torch

In [2]:
# 按照顺序生成
# 数据的索引：从左往右是从0开始，从右往左是从-1开始
tensor = torch.arange(2,14)
print(tensor)

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [3]:
print(tensor[2])

tensor(4)


In [ ]:
# 从1开始到4结束（不包括4，因此只有三个数！）
print(tensor[1:4])

tensor([3, 4, 5])


In [ ]:
# 最后的一个数是不算的！要取完整可以直接不写
print(tensor[2:-1])
print(tensor[2:])

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])


In [6]:
print(tensor[:5])

tensor([2, 3, 4, 5, 6])


In [ ]:
# 取最后的三个值
print(tensor[-3:])

tensor([11, 12, 13])


In [ ]:
# 就和列表一样选取数据
index = [1,3,4,5,5]
tensor[index]

tensor([3, 5, 6, 7, 7])

In [9]:
for t in tensor:
    print(t)

tensor(2)
tensor(3)
tensor(4)
tensor(5)
tensor(6)
tensor(7)
tensor(8)
tensor(9)
tensor(10)
tensor(11)
tensor(12)
tensor(13)
